### ISSUE TITLE
Keyboard Support

### ISSUE THREAD

**Issue by limbouser** [jwinarske/meta-flutter#11]
Does your version of flutter_wayland have keyboard support? When I tried a sample application in flutter_wayland, I could navigate properly using mouse but couldn't navigate using keyboard. Both on Ubuntu Linux and Pi. Could this be anything wrong from my side?

**Comment by jwinarske** [comment]
The existing keyboard handler sends raw key events via JSON over the platform channel.  For what you're looking for requires some minor code updates.

What's your timeline?

**Comment by limbouser** [comment]
I tried some other codes for keyboard support since I couldn't find it here and got an exception similar to https://github.com/flutter/flutter/issues/48442 . Just wanted to know if it was caused by the engine or the code. I had these issues only on Left and Down arrow keypress, Right and UP are working fine, and I am kind of stuck because of the same. So just close this issue when you fix Keyboard support in flutter_wayland.

**Comment by limbouser** [comment]
Hello @jwinarske , Did you get a chance to go through keyboard support? Can you check it with the latest master/stable and verify if you are getting https://github.com/flutter/flutter/issues/61711 anything similar to this? I really wanted a solution for this issue and it looks like an SDK issue to me.

**Comment by jwinarske** [comment]
closing this as meta-flutter is just a configuration layer.  Please file issues with the actual repo in question.  Thanks.
