### ISSUE TITLE
Error: Command 'cipd ensure -log-level error -root

### ISSUE THREAD

**Issue by YuvarajVelumani82** [jwinarske/meta-flutter#12]
Hi,

I am getting the below error when building the meta-flutter (originally downloaded from https://github.com/pub10cloud/meta-flutter, branch : develop/thud). 

```
wget: --user-agent: Invalid value ‘depot_tools/HEAD\n???’.
Error: Command 'cipd ensure -log-level error -root /home/yvelumani/code/rcar/build/tmp/work/aarch64-poky-linux/flutter-engine/git-r0/git -ensure-file /tmp/tmpjHd8PA.ensure' returned non-zero exit status 2
ERROR: Function failed: do_patch 'exit 1 from 'gclient.py sync --nohooks --no-history --revision 9e5072f0ce81206b99db3598da687a19ce57a863 -j 12 -v'
```

My build environment is setup on ubuntu 16.04 LTS and the I am using the flutter layer on the Poky revision: thud.
My intension to build and run flutter on the renesas-rcar-gen3 chipset which is based on meta-renesas revision:  refs/tags/thud-Yocto-v3.21.0.

Python version: 2.7.12 and 3.5.2
Default: python 2

In addition to renesas-rcar-gen3, I need to build for qualcomm-snapdragon-sa8155p platform as well. 
Kindly let me know if there is any additional step or packages that I need to install to build the image successfully. 

Thanks in advance.

**Comment by jwinarske** [comment]
You're welcome to submit a PR

**Comment by jwinarske** [comment]
again, do a git pull and rebuild
