### ISSUE TITLE
TARGET_GCC_VERSION 

### ISSUE THREAD

**Issue by embexus** [jwinarske/meta-flutter#21]
Hi in the README.md there is:

`TARGET_GCC_VRSION = "8.3.0"`

this is not the default gcc version in dunfell, is it a typo ?

**Comment by jwinarske** [comment]
It's not a typo.  It's there to show how to use it.  You don't need to
override it is you're doing a dunfell build.  So for dunfell don't add it
to local.conf.

**Comment by jwinarske** [comment]
Also keep in mind you're looking at the section title NVIDIA Xavier.  If you're targeting iMX8 then that would need adjustment per environment.
