### ISSUE TITLE
flutter_wayland start failed on core-image-weston

### ISSUE THREAD

**Issue by chong** [jwinarske/meta-flutter#36]
env already set
XDG_RUNTIME_DIR=/run/user/0/ ,
and weston-terminal or gtk3-demos works well

but flutter_wayland crash
flutter_wayland  /usr/share/flutter-gallery/sony/data

logs:
LOG: /usr/src/debug/flutter-wayland/git-r0/git/src/main.cc:65: Arg: /usr/share/flutter-gallery/sony/data/flutter_assets/
Keyboard Present
assets_path: /usr/share/flutter-gallery/sony/data/flutter_assets/
load_aot: 0
[ERROR:flutter/runtime/dart_vm_data.cc(18)] VM snapshot invalid and could not be inferred from settings.
[ERROR:flutter/runtime/dart_vm.cc(256)] Could not set up VM data to bootstrap the VM from.
[ERROR:flutter/runtime/dart_vm_lifecycle.cc(84)] Could not create Dart VM instance.
[FATAL:flutter/shell/common/shell.cc(143)] Check failed: vm. Must be able to initialize the VM.
Aborted

**Comment by jwinarske** [comment]
Do your SDK channel (engine version) and Engine channel (commit) match?

**Comment by chong** [comment]
flutter-gallery was build  with yocto, how to check the engine commit match ?

bitbake -c devshell flutter-gallery

root@lab:~/poky/build/tmp-glibc/work/armv8a-oe-linux/flutter-gallery/git-r0/git# ../../git-r0/recipe-sysroot-native/usr/share/flutter/sdk/bin/flutter  doctor


[✓] Flutter (Channel dev, 2.6.0-0.0.pre, on Ubuntu 20.04.3 LTS 5.4.0-81-generic, locale en_US.UTF-8)

root@lab:~/poky/build/tmp-glibc/work/armv8a-oe-linux/flutter-gallery/git-r0/git# ../../git-r0/recipe-sysroot-native/usr/share/flutter/sdk/bin/cache/dart-sdk/bin/dart --version
Dart SDK version: 2.15.0-42.0.dev (dev) (Sun Aug 22 13:00:21 2021 -0700) on "linux_x64"

**Comment by jwinarske** [comment]
closing as this is not related to software build issue.
