### ISSUE TITLE
Rasperry Pi example does not work as is

### ISSUE THREAD

**Issue by ghost** [jwinarske/meta-flutter#43]
First: Thanks for the great effort to bring flutter to embedded devices.

I tried to build & run the example for the raspberry-pi 4 given in the README and ran into some issues:

First I did not know how to actually run the flutter-gallery. It would be nice to add this to the readme:

```
flutter-pi /usr/share/flutter-gallery/flutter-assets
```

When running this, flutter-pi was unable to enumerate the DRI devices. The reason was that all kernel modules (expect i2c) were missing. I fixed that in `local.conf` with:

```
IMAGE_INSTALL_append = " kernel-modules"
```

After that flutter-pi could not find `/usr/share/flutter/icudtl.dat`. I fixed that issue with:

```
IMAGE_INSTALL_append = " flutter-engine"
```

The issue then was that flutter-engine was in release-mode while the gallery was in debug. I could not figure out how to put the gallery into release, but I was able to change the engine with

```
PACKAGECONFIG_pn-flutter-engine = "disable-desktop-embeddings embedder-for-target fontconfig full-dart-sd
k mode-debug"
```

I also stumbled across https://github.com/jwinarske/meta-flutter/issues/33#issuecomment-890282742 and applied the changes provided there to the flutter-gallery recipe, but I am not sure if that was actually needed.

**Comment by jwinarske** [comment]
@Flauer741 Hi.  Note repo has moved to https://github.com/meta-flutter/meta-flutter.  I have added a CI validation job there.  I will add RPI4 build to CI there.  It would be great to open issue there.  Cheers

**Comment by ghost** [comment]
Copied to new repo: https://github.com/meta-flutter/meta-flutter/issues/1
