### ISSUE TITLE
STM32MP157x yocto build fails

### ISSUE THREAD

**Issue by hilpara** [jwinarske/meta-flutter#44]
I used the commands you have for the STM32MP157x Discovery Board, but the build fails:
ERROR: Task (/home/poky/openstlinux/openstlinux-5.10-dunfell-mp1-21-03-31/layers/meta-flutter/recipes-graphics/flutter-engine/flutter-engine_git.bb:do_patch) failed with exit code '1'

Error: Command 'python3 src/flutter/tools/download_dart_sdk.py --fail-loudly' returned non-zero exit status 1

**Comment by jwinarske** [comment]
The readme indicates this repo migrated to https://github.com/meta-flutter/meta-flutter.git

Take a look at the CI job there.
