### ISSUE TITLE
vc4graphics and core-image-weston

### ISSUE THREAD

**Issue by limbouser** [jwinarske/meta-flutter#6]
`vc4graphics` as `MACHINE_FEATURES` is actually one of the hard dependencies for `core-image-weston`. If you disable `vc4graphics`, the image wouldn't be the same. Is it possible to make the `flutter_wayland` work with `vc4graphics` graphics disabled? 
It is disabled by adding 

`MACHINE_FEATURES_remove = " vc4graphics"`

Can you check on this or atleast provide me some guidance on how to make `flutter_wayland` work without `vc4graphics`?

**Comment by jwinarske** [comment]
Your local.conf setup is independent of the meta-flutter layer.  You need a Yocto local.conf / layer setup that builds the RDK stack as-is.

If you want to build the flutter_engine as-is against a target you don't have the Yocto config files for, use the embedded_flutter repo, and set it up to sync the sysroot from the target.  This will make the engine.  Chances are the custom link values will need overriding to account for different gcc version.

The main change would be in flutter_wayland.  Run the wayland scanner(++) on the westeros protocol file(s) to generate proper code/header(s).  Mostlikely not found in sysroot, but in RDK Westeros repo.  This change would happen in flutter_wayland's CMakeLists.txt.  An example of how it can be done is [here](https://github.com/jwinarske/clang_toolchain/blob/master/cmake/wayland/hello_wayland.cmake).

I figure flutter_wayland will need to support at least three compositors, most likely more.  Each one has additional protocols, or augmented from current.  If you can make the sysroot available to me I can look into the required changes.

**Comment by limbouser** [comment]
I was actually trying out your code on RPi and only thing I wanted was to disable the vc4graphics, but once I do that, it affects the whole image, actually the core-image-weston wasn't building properly after that. 
Is their any way I can run your code with vc4graphics disabled?

**Comment by jwinarske** [comment]
That's associated with meta-raspberrypi implementation.

meta-flutter is agnostic to mesa and wayland implementation.  I've build it for four different targets now, all use a different lower level.
